-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) as YEAR, MONTH(SALES_DATE) as MONTH, GENDER, COUNT(distinct s.USER_ID)
from USER_INFO as i join ONLINE_SALE as s on i.USER_ID = s.USER_ID
where GENDER is not null
group by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
order by YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER