# select ID, EMAIL, FIRST_NAME, LAST_NAME
# from DEVELOPERS 
# where substring(bin(SKILL_CODE), LENGTH(BIN(SKILL_CODE)) - 10, 1) = '1'
# or substring(bin(SKILL_CODE), LENGTH(BIN(SKILL_CODE)) - 8, 1) = '1'
# order by ID;


SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN ('Python', 'C#'))
ORDER BY ID ASC;