select a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, DATE_FORMAT(b.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
from USED_GOODS_BOARD a join USED_GOODS_REPLY b using (BOARD_ID)
where a.CREATED_DATE like '2022-10%'
order by b.CREATED_DATE, a.TITLE;